#
# Sample Makefile
#
# Put this file in the rundir directory
#
# Author: Mario Van Raemdonck
# Date  : 06/12/13


program:
	cd ../ && $(MAKE) program
	cp ../bin/ciflow.x ciflow.x

clean:
	rm -rf ciflow.x
	cd ../ && $(MAKE) clean
